### ISSUE TITLE
bytewise.decode breaks on SlowBuffer

### ISSUE THREAD

**Issue by mikeal** [deanlandolt/bytewise#1]
Found this when debugging some stuff with levelup.

```javascript
var buffer = require('buffer')
  , bytewise = require('bytewise')
  , key = bytewise.encode(['asdf',1,['asdf'],null])
  , slow = new buffers.SlowBuffer(key.length)
  ;
slow.copy(key)
bytewise.decode(slow)
```

```
TypeError: Cannot read property 'NaN' of undefined
    at SlowBuffer.get (buffer.js:303:21)
    at Object.decode (/Users/mikeal/Documents/git/pushdb/node_modules/bytewise/bytewise.js:117:21)
    at repl:1:11
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:754:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

**Comment by deanlandolt** [comment]
Whoops -- never closed this out.
